# Generated by Django 2.1.7 on 2019-02-27 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecuredEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('url', models.TextField()),
                ('file', models.FileField(upload_to='secure_url/files')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
