# Generated by Django 2.1.7 on 2019-02-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_url', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securedentity',
            old_name='password',
            new_name='password_salt',
        ),
        migrations.AlterField(
            model_name='securedentity',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='secure_url/files'),
        ),
        migrations.AlterField(
            model_name='securedentity',
            name='url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
