# Generated by Django 2.1.7 on 2019-02-27 22:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secure_url', '0003_securedentity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuredEntityAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterModelOptions(
            name='securedentity',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='securedentity',
            name='password_salt',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='securedentity',
            name='url',
            field=models.TextField(blank=True, default=None, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='securedentity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securedentityaccesslog',
            name='secured_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secure_url.SecuredEntity'),
        ),
    ]
