# Generated by Django 2.1.7 on 2019-02-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_agent_watchdog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useragentlog',
            options={'ordering': ('-created',)},
        ),
    ]
